# -*- coding: utf-8 -*-
"""course_functions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QCB72-a1VV4Jr72s7IgzRHEgJYsrQ0Cg
"""

## ----------------------------------------------------------------------##
##         !!!         DO NOT CHANGE THIS FILE           !!!             ##
## ----------------------------------------------------------------------##

# This notebook contains functions to easen the lcz - supy - netatmo workflow

import os
import numpy as np
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import matplotlib as mpl
from mpl_toolkits.axes_grid1 import make_axes_locatable
import xarray as xr
import warnings
warnings.filterwarnings("ignore")

def restructure_netatmo(net_file, grid_file, lcz_file, start_date, end_date, qc_level = 'o1'):

    ''' Restructure netatmo file to use in supy evaluation '''

    # Read the data
    print("Reading the data")
    df = pd.read_csv(net_file, index_col=0, parse_dates=True)

    print("Select qc-level and time range of interest")
    # Select the proper qc level
    df = df[df[qc_level] == True]

    # Select time range of interest
    df_sel = df.loc[start_date:end_date]

    # Get station information: id, lat, lon and altitude (z)
    df_stn = df_sel.drop_duplicates(subset='id', keep="first")[['p_id', 'lat', 'lon', 'z']]
    df_stn = df_stn.rename(columns={'p_id':'id'})

    print("Add SUEWS and LCZ grid labels to stations")
    # Add SUEWS and LCZ grid labels to stations
    gdf_stn = gpd.GeoDataFrame(
        df_stn, 
        geometry=gpd.points_from_xy(df_stn.lon, df_stn.lat)
        )
    gdf_stn.head()

    # Add SUPY gridID, via spatial join
    gdf_grid = gpd.read_file(grid_file)
    gdf_stn_new = gpd.tools.sjoin(gdf_stn, gdf_grid, how='left')

    # Clean-up a bit: remove columns, grid_id as index, and remove 
    # netatmo stations that fall outside of the SUEWS grid extent.
    gdf_stn_new.drop(['index_right'],axis=1, inplace=True)
    gdf_stn_new.rename(columns={
        'id_right':'grid_id',
        'id_left' :'netatmo_id',}, inplace=True)
    gdf_stn_new = gdf_stn_new[gdf_stn_new['grid_id'].notna()]
    gdf_stn_new = gdf_stn_new.set_index('grid_id')
    gdf_stn_new.index = gdf_stn_new.index.astype(int)

    # Also add LCZ class, from lczFilter layer
    lczData = xr.open_rasterio(f"{lcz_file}")
    LCZs = []
    for stn_i in range(gdf_stn_new.shape[0]):
        LCZ = int(lczData[0,:,:].sel(
            x=gdf_stn_new.iloc[stn_i]['lon'],
            y=gdf_stn_new.iloc[stn_i]['lat'],
            method="nearest").values)
        LCZs = LCZs + [LCZ]
    gdf_stn_new['LCZ'] = LCZs

    # Save to csv file
    net_stn_file = net_file.replace('netatmo_amsterdam_2019_QC', f'netatmo_qc_stn_{start_date}_{end_date}')
    gdf_stn_new.to_csv(net_stn_file)

    # Save to ESRI Shapfile
    gdf_stn_new.to_file(driver = 'ESRI Shapefile', 
                                filename = net_stn_file.replace('.csv','.shp'))

    print(f"The restructured Netatmo station file has been saved to:\n - {net_stn_file}\n - {net_stn_file.replace('.csv','.shp')}")

    # Select relevant observations, and rename
    # Only stations within domain
    df_sel_new = df_sel[df_sel['p_id'].isin(gdf_stn_new.netatmo_id)]

    # Set date without UTC
    df_sel_new['date'] = df_sel_new.index.tz_localize(None)

    # Select relevant variables
    df_obs = df_sel_new[['p_id', 'date', 'ta_int', 'max_temp','min_temp','humidity','max_humidity','min_humidity']]

    df_obs.rename(columns={
        "p_id":'id',
        "ta_int": "T2",
        "max_temp": "T2max",
        "min_temp": "T2min",
        "humidity": "RH2",
        "max_humidity": "RH2max",
        "min_humidity": "RH2min",
        }, inplace=True)

    # Save to file
    net_obs_file = net_file.replace('netatmo_amsterdam_2019_QC', f'netatmo_qc_obs_{start_date}_{end_date}')
    df_obs.to_csv(net_obs_file, index=None)

    print(
        f"The restructured Netatmo observation file has been saved to:\n - {net_obs_file}"
        )


def _get_color_schemes(scheme):
    '''helper function to get color schemes'''

    cb = {
        'lcz': [
            '#8c0000', '#d10000', '#ff0000', '#bf4d00',
            '#ff6600', '#ff9955', '#faee05', '#bcbcbc',
            '#ffccaa', '#555555', '#006a00', '#00aa00',
            '#648525', '#b9db79', '#000000', '#fbf7ae', '#6a6aff'],

        # 'Paved (-)', 'Buildings (-)', 'Grass (-)',
        # 'Deciduous trees (-)', 'Evergreen trees (-)', 'Bare soil (-)', 'Water (-)'
        'suews': [
            '#4d4d4d', '#d05e5e', '#c5f776',
            '#5ac18e', '#156475', '#99774d', '#6a6aff']
    }

    return cb[scheme]


def map_lcz_grid(grid_file, lcz_file,f_dir, net_stn_file):

    ''' Plot the LCZ map, the grid and grid ID numbers in figure '''

    # Define LCZ colors, make cmap
    cb_lcz = _get_color_schemes('lcz')
    
    cmap = mpl.colors.ListedColormap(cb_lcz)
    cmap.set_bad(color='white')
    cmap.set_under(color='white')

    # Read clipped LCZ map and grid
    lczTif = xr.open_rasterio(lcz_file)[0,:,:]
    gdf_grid = gpd.read_file(grid_file)

    # Initialize figures
    fig, ax = plt.subplots(figsize=(15, 10))

    # Add lcz map 
    im = lczTif.plot(
        cmap=cmap, vmin=1, vmax=17,
        ax=ax, add_colorbar=False,
    )

    cb_labels = np.arange(1,18,1)
    cb = plt.colorbar(
        im,
        ticks=np.linspace(1.5, 17-0.5, 17),
        orientation='horizontal', pad=0.08, shrink=0.8
    )
    cb.set_ticklabels(cb_labels)
    cb.set_label(label='LCZ Class', fontsize=11)
    cb.ax.tick_params(labelsize=11)

    gdf_grid.plot(ax=ax, facecolor='none', edgecolor='black')

    # Add grid cell numbers to map
    gdf_grid = gdf_grid.set_index("id")
    def getXY(pt):
        return (pt.x, pt.y)
    centroidseries = gdf_grid['geometry'].centroid
    lons,lats = [list(t) for t in zip(*map(getXY, centroidseries))]
    for i in range(len(lons)):
        ax.text(lons[i],lats[i],int(gdf_grid.index[i]),fontsize=13)
    
    # Add netatmo stations
    net_stn = pd.read_csv(net_stn_file,index_col=0)
    gdf_net_stn = gpd.GeoDataFrame(
        net_stn, 
        geometry=gpd.points_from_xy(net_stn.lon, net_stn.lat))
    gdf_net_stn.plot(marker="*",color="#e24afc", 
                     markersize=200, edgecolor='w', ax=ax)
        
    # Some axes aesthetics
    ax.tick_params(axis='both', which='major', labelsize=13)
    ax.set_xlabel('° Longitude', fontsize=13)
    ax.set_ylabel('° Latitude', fontsize=13)
    ax.set_title('')

    # Save to file
    plt.tight_layout()
    plt.savefig(f"{f_dir}/map_lcz_grid_netatmo.jpg",dpi=300)
    plt.close('all')
    

def plot_gridcell_fractions(df_grid_suews, df_grid_lcz, f_dir):
    
    ''' Two barplots with LCZ and SUEWS land cover fraction per grid ID'''
    
    # Get the colors
    cb_lcz   = _get_color_schemes('lcz')
    cb_suews = _get_color_schemes('suews')

    # Make the figure
    fig, (ax1,ax2) = plt.subplots(1,2, 
                                  figsize=(14,30),
                                  sharey=True)

    df_grid_lcz\
        .plot.barh(stacked=True, color=cb_lcz, ax=ax1)
    ax1.legend(loc='upper center',bbox_to_anchor=(0.5, -0.02), ncol=5)
    ax1.set_xlabel('LCZ fraction (-)')
    ax1.set_ylabel('Grid ID')

    df_grid_suews[['Paved (-)', 'Buildings (-)', 'Grass (-)', 'Deciduous trees (-)',
           'Evergreen trees (-)', 'Bare soil (-)', 'Water (-)']]\
        .plot.barh(stacked=True, color=cb_suews, ax=ax2)
    ax2.legend(loc='upper center',bbox_to_anchor=(0.5, -0.02), ncol=3)
    ax2.set_xlabel('SUEWS land cover fraction (-)')

    plt.tight_layout()
    
    fig.savefig(os.path.join(
        f_dir,
        f"Grid_cell_fractions.jpg"),
                dpi = 300)
    plt.close('all')
        
    
def save_net_stn_to_shapefile(net_stn_file):
    
    ''' Save netatmo station locations as shapefile '''
    
    net_stn = pd.read_csv(net_stn_file,index_col=False)
    gdf_net_stn = gpd.GeoDataFrame(
        net_stn, geometry=gpd.points_from_xy(net_stn.lon, net_stn.lat))
    
    # Clean-up a bit.
    gdf_net_stn_clean = gdf_net_stn[['id','geometry']]
    
    # Save
    gdf_net_stn_clean.to_file(driver = 'ESRI Shapefile', 
                              filename = net_stn_file.replace('.csv','.shp'))
    
    
    
def assign_gridid_lcz_to_netatmo_stn(net_stn_file,grid_file,lcz_file):
    
    # Read netatmo station table
    net_stn = pd.read_csv(net_stn_file,index_col=False)
    gdf_net_stn = gpd.GeoDataFrame(
        net_stn, 
        geometry=gpd.points_from_xy(net_stn.lon, net_stn.lat)
        )

    # Add SUPY gridID, via spatial join
    gdf_grid = gpd.read_file(grid_file)
    net_stn_new = gpd.tools.sjoin(gdf_net_stn, gdf_grid, how='left')

    # Also add LCZ class, from lczFilter layer
    lczData = xr.open_rasterio(f"{lcz_file}")

    for stn_i in range(net_stn.shape[0]):
        net_stn_new.loc[stn_i,'LCZ'] = int(lczData[1,:,:].sel(
            x=net_stn['lon'][stn_i],
            y=net_stn['lat'][stn_i],
            method="nearest").values)

    # Clean-up a bit: remove columns, grid_id as index, and remove 
    # netatmo stations that fall outside of the SUEWS grid extent.
    net_stn_new.drop(['index_right','dummy'],axis=1, inplace=True)
    net_stn_new.rename(columns={
        'id_right':'grid_id',
        'id_left' :'netatmo_id',}, inplace=True)
    net_stn_new = net_stn_new[net_stn_new['grid_id'].notna()]
    net_stn_new = net_stn_new.set_index('grid_id')
    net_stn_new.index = net_stn_new.index.astype(int)

    #print('# netatmo stations per',net_stn_new.groupby('grid_id')['netatmo_id'].nunique())
    #print('# netatmo stations per',net_stn_new.groupby('LCZ')['netatmo_id'].nunique())

    return net_stn_new


def plot_timeseries_grid_cell(grid_id_sel, sub_start, sub_end, 
                              f_dir, net_stn, net_obs, df_output):
    
    ''' Plots timeseries of T2 and RH2 for a grid cell of choice.
    If netatmo stations are available for that grid cell, they are 
    added as well. In addition, correlation and bias are provided.'''

    plt.rcParams.update({'font.size': 12})
    cb_lcz = _get_color_schemes('lcz')
    vars_to_plot = ['T2']

    fig, axes = plt.subplots(1, 1, figsize=(16,4))

    # Find netatmo ID's within grid ID nr X
    net_id_sel = list(net_stn[net_stn.index == grid_id_sel].netatmo_id)
    len(net_id_sel)

    for v_i, v in enumerate(vars_to_plot):

        # If netatmo stations available in grid cell, plot single stations.
        if len(net_id_sel) > 0:

            # Single station information
            for net_id_i in net_id_sel:
                net_obs_sel = net_obs[net_obs.id == net_id_i][v]
                net_obs_sel = net_obs_sel.resample('1H').last()
                net_obs_sel = net_obs_sel.loc[sub_start:sub_end]
                if not net_obs_sel.empty:
                  net_obs_sel.plot(ax=axes, legend=False, lw=1,
                      color=cb_lcz[int(net_stn[net_stn.netatmo_id == net_id_i]['LCZ'])-1])
                  net_obs_avg = net_obs_sel

        # If # netatmo > 1, also plot average
        if len(net_id_sel) > 1:
            net_obs_avg = net_obs[net_obs.id.isin(net_id_sel)][v]\
                .loc[sub_start:sub_end]\
                .groupby('date').mean()
            net_obs_avg.plot(ax=axes,linestyle='--', color="#9932cc", lw=2)

        list_grid = pd.to_numeric(df_output.index.levels[0], downcast="integer")
        df_output.index = df_output.index.set_levels(list_grid, level=0)
        df_output = df_output.sort_index()

        suews_sel = df_output.loc[grid_id_sel, [v]]\
            .loc[sub_start:sub_end]
        suews_sel.plot(ax=axes, color='black', legend=False,lw=2)

        # Also add few statistics, if netatmo stations are available
        if len(net_id_sel) > 0:
            tmp = pd.merge(suews_sel,pd.DataFrame(net_obs_avg), how='inner', left_index=True, right_index=True)
            corr = np.round(tmp[v+'_x'].corr(tmp[v+'_y']),2)
            bias = np.round((tmp[v+'_x']-tmp[v+'_y']).mean(),2)
            print(corr, bias)

            axes.set_title(f'Correlation: {corr} | Bias: {bias} ',loc='right')

    axes.set_ylabel('2m Temperature ($^\circ C$)')
    #axes[1].set_ylabel('2m Relative Humidity (%)')

    # Add custom legend in top panel
    custom_lines = [Line2D([0], [0], color='black', lw=2),
                    Line2D([0], [0], color='#ff0000', lw=1),
                    Line2D([0], [0], color='#9932cc', lw=2, ls='--')]

    axes.legend(custom_lines, ['SUEWS','Netatmo station (LCZ color)', 'Netatmo average'])

    axes.set_title(f'Grid ID: {grid_id_sel} | # Netatmo stations: {len(net_id_sel)} ',loc='left')

    plt.tight_layout()

    fig.savefig(os.path.join(
        f_dir,
        f"plot_timeseries_grid_cell_{grid_id_sel}_{sub_start}_{sub_end}.jpg"),
                dpi = 300)

    
def plot_diurnal_cycle_grid_cell(grid_id_sel, sub_start, sub_end, 
                              f_dir, net_stn, net_obs, df_output):
    
    ''' Plots diurnal cycle of T2 and RH2 for a grid cell of choice.
        If netatmo stations are available for that grid cell, they are 
        added as well.'''
    
    plt.rcParams.update({'font.size': 14})
    cb_lcz = _get_color_schemes('lcz')
    vars_to_plot = ['T2']

    fig, axes = plt.subplots(1, 1, figsize=(10,10))

    # Find netatmo ID's within grid ID nr X
    net_id_sel = list(net_stn[net_stn.index == grid_id_sel].netatmo_id)
    len(net_id_sel)

    for v_i, v in enumerate(vars_to_plot):

        # If netatmo stations available in grid cell, plot single stations.
        if len(net_id_sel) > 0:

            # Single station information
            for net_id_i in net_id_sel:
                net_obs_sel = net_obs[net_obs.id == net_id_i][v]
                net_obs_sel = net_obs_sel.resample('1H').last()
                net_obs_sel= net_obs_sel.loc[sub_start:sub_end]
                obs_mean = pd.DataFrame(net_obs_sel.groupby(net_obs_sel.index.hour).mean())
                obs_std = pd.DataFrame(net_obs_sel.groupby(net_obs_sel.index.hour).std())

                axes.plot(obs_mean.index,obs_mean[v],
                               color=cb_lcz[int(net_stn[net_stn.netatmo_id == net_id_i]['LCZ'])-1])
                axes.fill_between(obs_mean.index,
                                 obs_mean[v]-obs_std[v],
                                 obs_mean[v]+obs_std[v],
                                 color=cb_lcz[int(net_stn[net_stn.netatmo_id == net_id_i]['LCZ'])-1],
                                 alpha=0.1)

        list_grid = pd.to_numeric(df_output.index.levels[0], downcast="integer")
        df_output.index = df_output.index.set_levels(list_grid, level=0)
        df_output = df_output.sort_index()

        suews_sel = df_output.loc[grid_id_sel, [v]]\
            .loc[sub_start:sub_end]
        suews_mean = suews_sel.groupby(suews_sel.index.hour).mean()
        suews_std = suews_sel.groupby(suews_sel.index.hour).std()

        axes.errorbar(suews_mean.index,suews_mean[v], suews_std[v], 
                           linestyle='None', marker='^', color='black',lw=2)

    axes.set_ylabel('2m Temperature ($^\circ C$)')
    #axes[1].set_ylabel('2m Relative Humidity (%)')

    axes.set_xlabel('Hour of the day (UTC)')
    #axes[1].set_xlabel('Hour of the day (UTC)')

    # Add custom legend in top panel
    custom_lines = [Line2D([0], [0], color='black', lw=2),
                    Line2D([0], [0], color='#ff0000', lw=1)]
    axes.legend(custom_lines, ['SUEWS','Netatmo station (LCZ color)'], loc='lower left')

    axes.set_title(f'Grid ID: {grid_id_sel} | # Net stat.: {len(net_id_sel)} ',loc='left')

    plt.tight_layout()
    
    fig.savefig(os.path.join(
        f_dir,
        f"plot_diurnal_cycle_grid_cell_{grid_id_sel}_{sub_start}_{sub_end}.jpg"),
                dpi = 300)

    
def plot_timeseries_suews_vars_grid_cell(grid_id_sel, sub_start, sub_end, 
                                         var_list, df_output, f_dir):
    
    ''' Plot output variables of choice, for (sub-)period of choice, 
    for one grid cells of choice, all in same plot. '''
        
    plt.rcParams.update({'font.size': 14})
    
    list_grid = pd.to_numeric(df_output.index.levels[0], downcast="integer")
    df_output.index = df_output.index.set_levels(list_grid, level=0)
    df_output = df_output.sort_index()

    fig, ax = plt.subplots(1,1,figsize=[12, 5])
    ax = (
        df_output.loc[grid_id_sel, var_list]
        .loc[sub_start:sub_end]
        .plot(ax=ax)
        .legend(loc='center left',bbox_to_anchor=(1.0, 0.5))
    )
    
    plt.tight_layout()
    
    fig.savefig(os.path.join(
        f_dir,
        f"plot_timeseries_suews_vars_grid_cell_{grid_id_sel}_{sub_start}_{sub_end}.jpg"),
                dpi = 300)
    
    
def plot_timeseries_suews_vars_two_cells(gridID_1, gridID_2, sub_start, sub_end, 
                                         var_list, df_output, f_dir):

    ''' Plot output variables of choice, for (sub-)period of choice, 
        for two grid cells of choice. Each variable has its own subplot '''

    import matplotlib.pyplot as plt
    plt.rcParams.update({'font.size': 14})
    
    fig, axes = plt.subplots(len(var_list),1,figsize=[12, 4*len(var_list)],
                            sharex=True)

    for v_i, v in enumerate(var_list):

        if len(var_list) == 1:  
            ax_target = axes
        else:
            ax_target = axes[v_i]

        df_output.loc[gridID_1, v]\
            .loc[sub_start:sub_end]\
            .plot(ax=ax_target, label=gridID_1)\
            .legend(loc='upper left')

        df_output.loc[gridID_2, v]\
            .loc[sub_start:sub_end]\
            .plot(ax=ax_target, label=gridID_2)\
            .legend(loc='upper left')
        ax_target.set_ylabel(v)

    plt.tight_layout()

    fig.savefig(os.path.join(
        f_dir,
        f"plot_timeseries_suews_vars_two_cells_{gridID_1}_{gridID_2}_{sub_start}_{sub_end}.jpg"),
                dpi = 300)
    

def plot_intra_suews_grid_variability(var, sub_start, sub_end,
                                      df_grid_suews, df_output, f_dir,
                                      vmin, vmax):
    
    '''Plot intra suews grid variability for suews variables'''
    
    plt.rcParams.update({'font.size': 14})
    x_ticks = np.arange(-0.05,1.1,0.1)
    
    # Prepare output data structure
    list_grid = pd.to_numeric(df_output.index.levels[0], downcast="integer")
    df_output.index = df_output.index.set_levels(list_grid, level=0)
    df_output = df_output.sort_index()

    # Get day and night based on Kdown from SUEWS output
    suews_kdown = df_output.loc[1,'Kdown'].loc[sub_start:sub_end]
    day_timesteps = suews_kdown[suews_kdown > 0].index
    night_timesteps = suews_kdown[suews_kdown == 0].index

    # Get imperviousness
    df_grid_suews['IMP'] = df_grid_suews['Paved (-)'] + df_grid_suews['Buildings (-)']

    # Initialize figure
    fig, ax = plt.subplots(1,3, figsize=(20,7), sharey=True)

    # Loop over bins of imperviousness
    for imp_i, imp in enumerate(np.arange(0,0.91,0.1)):

        grid_id_sel   = df_grid_suews['IMP'][(df_grid_suews['IMP'] >= imp) 
                                             & (df_grid_suews['IMP'] < imp+0.1)].index

        if len(grid_id_sel) != 0:

            suews_sel       = df_output.loc[grid_id_sel, [var]]\
                                    .droplevel('grid')\
                                    .loc[sub_start:sub_end]
            suews_sel_day   = suews_sel.loc[day_timesteps]
            suews_sel_night = suews_sel.loc[night_timesteps]

            # Plot all hour mean
            ax[0].errorbar(imp+0.05, suews_sel.mean().mean(), 
                           suews_sel.std().values[0],
                           linestyle='None', marker='o',lw=1, markersize=10,
                           color = '0.2')
            ax[0].set_title('Daily mean')
            ax[0].set_ylim(vmin,vmax)

            ax[0].text(np.linspace(0,1,12)[imp_i+1],0.95, str(len(grid_id_sel )),
                    verticalalignment='bottom', horizontalalignment='center',
                    transform=ax[0].transAxes,
                    color='purple', fontsize=12)

            # Plot day only mean
            ax[1].errorbar(imp+0.05, suews_sel_day.mean().mean(), 
                           suews_sel_day.std().values[0],
                           linestyle='None', marker='o',lw=1, markersize=10,
                           color = '0.2')
            ax[1].set_title('Day-time (Kdown > 0)')

            # Plot night only mean
            ax[2].errorbar(imp+0.05, suews_sel_night.mean().mean(), 
                           suews_sel_night.std().values[0],
                           linestyle='None', marker='o',lw=1, markersize=10,
                           color = '0.2')
            ax[2].set_title('Night-time (Kdown = 0)')

    for i in range(3):
        ax[i].set_xlabel('Imperviousness')
        ax[i].set_xticks(x_ticks)
        ax[i].set_xticklabels(np.around(np.arange(-0.05,1.1,0.1),2))
        xticks = ax[i].xaxis.get_major_ticks()
        xticks[0].label1.set_visible(False)
        xticks[-1].label1.set_visible(False)
        ax[i].grid(ls='--',color='0.8',zorder=-10)

    ax[0].set_ylabel(var)

    plt.tight_layout()

    fig.savefig(os.path.join(
        f_dir,
        f"plot_intra_suews_grid_variability_{var}_{sub_start}_{sub_end}.jpg"),
                dpi = 300)

def map_time_slice_suews(time_slice, var_list, 
                        df_output, grid_file, f_dir):
    
    df_res_plot = (
        df_output.swaplevel(axis=0)
        .sort_index()
        .loc[time_slice]
        .droplevel("datetime")
    )

    # merge supy results into geopandas dataframe for geoplotting
    gdf_grid = gpd.read_file(grid_file)
    gdf_grid.index = gdf_grid.id.astype(int)
    df_res_plot.index = df_res_plot.index.astype(float).astype(int)
    gdf_grid_plot = gdf_grid.merge(df_res_plot, left_index=True, right_index=True)

    if len(var_list) > 4:
        print("Please provide a maximum of 4 variables. Abort. ")
    
    else:
        if len(var_list) == 1:
            fig, ax = plt.subplots(1,1, figsize=(5,5))
            
            divider = make_axes_locatable(ax)
            cax = divider.append_axes("right", size="5%", pad=-0.5)

            gdf_grid_plot.plot(column=var_list[0], ax=ax,legend=True,cax=cax)
            ax.set_title(var_list[0])
            
        else:
            fig, axs = plt.subplots(1,len(var_list), figsize=(5*len(var_list),5), 
                                    sharex=True, sharey=True)
            axes = axs.ravel()
            plt.subplots_adjust(wspace=0.0002, hspace=-0.05)

            for v_i, v in enumerate(var_list):

                divider = make_axes_locatable(axes[v_i])
                cax = divider.append_axes("right", size="5%", pad=-0.5)

                gdf_grid_plot.plot(column=v, ax=axes[v_i],legend=True,cax=cax)
                axes[v_i].set_title(v)

        plt.tight_layout()

        fig.savefig(os.path.join(
        f_dir,
        f"map_{time_slice.replace(' ','')}_suews_{'_'.join(var_list)}.jpg"),
                dpi = 300)
    

def plot_intra_lcz_variability(var, sub_start, sub_end,
                               net_obs, net_stn, df_output, f_dir):
    
    '''Plot intra-lcz variability for netatmo stations'''
    
    plt.rcParams.update({'font.size': 14})
    
    # Get day and night based on Kdown from SUEWS output
    list_grid = pd.to_numeric(df_output.index.levels[0], downcast="integer")
    df_output.index = df_output.index.set_levels(list_grid, level=0)
    df_output = df_output.sort_index()
    suews_kdown = df_output.loc[1,'Kdown'].loc[sub_start:sub_end]

    day_timesteps = suews_kdown[suews_kdown > 0].index
    night_timesteps = suews_kdown[suews_kdown == 0].index

    # Initialize figure
    cb_lcz = _get_color_schemes('lcz')
    fig, ax = plt.subplots(1,3, figsize=(20,7), sharey=True)

    # Reduce netatmo to (sub-)period
    net_obs_sub = net_obs.loc[sub_start:sub_end]

    # Netatmo series contains missing timestamps. Clean up this dataframe.
    net_obs_clean = pd.pivot_table(net_obs_sub, values=var, index="date", columns="id")
    net_obs_clean = net_obs_clean.asfreq('1H')

    # Cross-check netatmo ID's with Obs ID's available for the selected period
    net_stn_cross = net_stn[net_stn.netatmo_id.isin(net_obs_clean.columns)]
    net_obs_clean = net_obs_clean[net_stn_cross.netatmo_id]


    # Loop over LCZ classes
    for lcz_i in range(1,18,1):

        lcz_net_id_sel = list(net_stn_cross[net_stn_cross.LCZ == lcz_i].netatmo_id)

        if len(lcz_net_id_sel) != 0:

            # Extract relevant netatmo data
            net_obs_sel = net_obs_clean[lcz_net_id_sel]
            net_obs_sel_day = net_obs_sel.loc[day_timesteps]
            net_obs_sel_night = net_obs_sel.loc[night_timesteps]

            # Plot all hour mean
            ax[0].errorbar(lcz_i, net_obs_sel.mean().mean(), 
                           net_obs_sel.std().std(),
                           linestyle='None', marker='o',lw=1, markersize=10,
                           color = cb_lcz[lcz_i-1])
            ax[0].set_title('Daily mean')

            ax[0].text(lcz_i/18, 0.02, str(len(lcz_net_id_sel)),
                    verticalalignment='bottom', horizontalalignment='center',
                    transform=ax[0].transAxes,
                    color='purple', fontsize=11)

            # Plot day only mean
            ax[1].errorbar(lcz_i, net_obs_sel_day.mean().mean(), 
                           net_obs_sel_day.std().std(),
                           linestyle='None', marker='o',lw=1, markersize=10,
                           color = cb_lcz[lcz_i-1])
            ax[1].set_title('Day-time (Kdown > 0)')

            # Plot night only mean
            ax[2].errorbar(lcz_i, net_obs_sel_night.mean().mean(), 
                           net_obs_sel_night.std().std(),
                           linestyle='None', marker='o',lw=1, markersize=10,
                           color = cb_lcz[lcz_i-1])
            ax[2].set_title('Night-time (Kdown = 0)')

    for i in range(3):
        ax[i].set_xlabel('LCZ Class')
        ax[i].set_xticks(range(0,19,1))
        ax[i].set_xticklabels(range(0,19,1))
        xticks = ax[i].xaxis.get_major_ticks()
        xticks[0].label1.set_visible(False)
        xticks[-1].label1.set_visible(False)
        ax[i].grid(ls='--',color='0.8',zorder=-10)

    ax[0].set_ylabel(var)

    plt.tight_layout()
    
    fig.savefig(os.path.join(
        f_dir,
        f"plot_intra_lcz_variability_{var}_{sub_start}_{sub_end}.jpg"),
                dpi = 300)
    

def plot_timeseries_flux_obs(up_flux_file, sub_start, sub_end, 
                                         var_list, df_output, f_dir):
    
    ''' Plot output variables of choice, for (sub-)period of choice, all in same plot. '''
        
    plt.rcParams.update({'font.size': 14})

    df_flux = pd.read_csv(up_flux_file, index_col=0, parse_dates=True)
    
    fig, ax = plt.subplots(1,1,figsize=[15, 5])
    ax = (
        df_flux.loc[:, var_list]
        .loc[sub_start:sub_end]
        .plot(ax=ax)
        .legend(loc='center left',bbox_to_anchor=(1.0, 0.5))
    )

    plt.tight_layout()
    
    fig.savefig(os.path.join(
        f_dir,
        f"plot_timeseries_flux_obs_{sub_start}_{sub_end}.jpg"),
                dpi = 300)
    

def plot_diurnal_cycle_flux_obs(up_flux_file, sub_start, sub_end, f_dir):

    plt.rcParams.update({'font.size': 14})
    vars_to_plot = ['QN','QH', 'QE', 'QS']

    # Read the flux tower data
    df_flux = pd.read_csv(up_flux_file, index_col=0, parse_dates=True)

    # Subset dates
    flux_obs_sel = df_flux[sub_start:sub_end]

    # Make the plot
    fig, axes = plt.subplots(1, 4, figsize=(20,5))

    obs_mean = pd.DataFrame(flux_obs_sel.groupby(flux_obs_sel.index.hour).mean())
    obs_std = pd.DataFrame(flux_obs_sel.groupby(flux_obs_sel.index.hour).std())

    for v_i, v in enumerate(vars_to_plot):

        axes[v_i].plot(obs_mean.index, obs_mean[v])
        axes[v_i].fill_between(obs_mean.index,
                            obs_mean[v]-obs_std[v],
                            obs_mean[v]+obs_std[v],
                            alpha=0.1)
        axes[v_i].set_title(v)
        axes[v_i].set_ylabel('Flux [W/m²]')
        axes[v_i].set_xlabel('Hour of the day (UTC)')

    plt.tight_layout()

    fig.savefig(os.path.join(
        f_dir,
        f"plot_diurnal_cycle_flux_obs_{sub_start}_{sub_end}.jpg"),
                dpi = 300)






def _legend_without_duplicate_labels(ax):
    
    ''' Helper function to add legend in plot below'''
    
    handles, labels = ax.get_legend_handles_labels()
    unique = [(h, l) for i, (h, l) in enumerate(zip(handles, labels)) if l not in labels[:i]]
    ax.legend(*zip(*unique), loc='upper left')

    
def plot_intra_suews_netatmo_variability(var, sub_start, sub_end,
                                         net_stn, net_obs, df_grid_suews, df_output, f_dir,
                                         vmin, vmax):
   
    '''Plot intra grid variability for suews output and LCZ variables'''

    plt.rcParams.update({'font.size': 14})
    x_ticks = np.arange(-0.05,1.1,0.1)

    # Prepare output data structure
    list_grid = pd.to_numeric(df_output.index.levels[0], downcast="integer")
    df_output.index = df_output.index.set_levels(list_grid, level=0)
    df_output = df_output.sort_index()

    # Get day and night based on Kdown from SUEWS output
    suews_kdown = df_output.loc[1,'Kdown'].loc[sub_start:sub_end]
    day_timesteps = suews_kdown[suews_kdown > 0].index
    night_timesteps = suews_kdown[suews_kdown == 0].index

    # Reduce netatmo to (sub-)period
    net_obs_sub = net_obs.loc[sub_start:sub_end]

    # Netatmo series contains missing timestamps. Clean up this dataframe.
    net_obs_clean = pd.pivot_table(net_obs_sub, values=var, index="date", columns="id")
    net_obs_clean = net_obs_clean.asfreq('1H')

    # Cross-check netatmo ID's with Obs ID's available for the selected period
    net_stn_cross = net_stn[net_stn.netatmo_id.isin(net_obs_clean.columns)]
    net_obs_clean = net_obs_clean[net_stn_cross.netatmo_id]

    # Get imperviousness
    df_grid_suews['IMP'] = df_grid_suews['Paved (-)'] + df_grid_suews['Buildings (-)']

    # Initialize figure
    fig, ax = plt.subplots(1,3, figsize=(20,7), sharey=True)

    # Loop over bins of imperviousness
    for imp_i, imp in enumerate(np.arange(0,0.91,0.1)):

        grid_id_sel   = df_grid_suews['IMP'][(df_grid_suews['IMP'] >= imp) 
                                             & (df_grid_suews['IMP'] < imp+0.1)].index

        if len(grid_id_sel) != 0:

            # Get the SUEWS data
            suews_sel       = df_output.loc[grid_id_sel, [var]]\
                                    .droplevel('grid')\
                                    .loc[sub_start:sub_end]
            suews_sel_day   = suews_sel.loc[day_timesteps]
            suews_sel_night = suews_sel.loc[night_timesteps]

            # Find netatmo ID's within grid ID nr X
            net_id_sel = list(net_stn_cross[net_stn_cross.index.isin(grid_id_sel)].netatmo_id)

            # Extract relevant netatmo data
            net_obs_sel = net_obs_clean[net_id_sel]
            net_obs_sel_day = net_obs_sel.loc[day_timesteps]
            net_obs_sel_night = net_obs_sel.loc[night_timesteps]

            # Plot all hour mean
            ax[0].errorbar(imp+0.035, suews_sel.mean().mean(), 
                           suews_sel.std().values[0],
                           linestyle='None', marker='o',lw=1, markersize=10,
                           color = '0.2')
            ax[0].errorbar(imp+0.065, net_obs_sel.mean().mean(), 
                   net_obs_sel.std().std(),
                   linestyle='None', marker='o',lw=1, markersize=10,
                   color = '0.8')
            ax[0].set_title('Daily mean')
            ax[0].set_ylim(vmin,vmax)

            ax[0].text(np.linspace(0,1,12)[imp_i+1],0.95, str(len(grid_id_sel)),
                    verticalalignment='bottom', horizontalalignment='center',
                    transform=ax[0].transAxes,
                    color='purple', fontsize=12)
            ax[0].text(np.linspace(0,1,12)[imp_i+1],0.90, str(len(net_id_sel)),
                    verticalalignment='bottom', horizontalalignment='center',
                    transform=ax[0].transAxes,
                    color='#FF1493', fontsize=12)

            ax[1].errorbar(imp+0.035, suews_sel_day.mean().mean(), 
                   suews_sel_day.std().values[0],
                   linestyle='None', marker='o',lw=1, markersize=10,
                   color = '0.2')
            ax[1].errorbar(imp+0.065, net_obs_sel_day.mean().mean(), 
                   net_obs_sel_day.std().std(),
                   linestyle='None', marker='o',lw=1, markersize=10,
                   color = '0.8')
            ax[1].set_title('Day-time (Kdown > 0)')

            ax[2].errorbar(imp+0.035, suews_sel_night.mean().mean(), 
                   suews_sel_night.std().values[0],
                   linestyle='None', marker='o',lw=1, markersize=10,
                   color = '0.2',label='SUEWS')
            ax[2].errorbar(imp+0.065, net_obs_sel_night.mean().mean(), 
                   net_obs_sel_night.std().std(),
                   linestyle='None', marker='o',lw=1, markersize=10,
                   color = '0.8',label='Netatmo')
            ax[2].set_title('Night-time (Kdown = 0)')


    for i in range(3):
        ax[i].set_xlabel('Imperviousness')
        ax[i].set_xticks(x_ticks)
        ax[i].set_xticklabels(np.around(np.arange(-0.05,1.1,0.1),2))
        xticks = ax[i].xaxis.get_major_ticks()
        xticks[0].label1.set_visible(False)
        xticks[-1].label1.set_visible(False)
        ax[i].grid(ls='--',color='0.8',zorder=-10)

    ax[0].set_ylabel(var)
       
    _legend_without_duplicate_labels(ax[2])

    plt.tight_layout()

    fig.savefig(os.path.join(
        f_dir,
        f"plot_intra_suews_netatmo_variability_{var}_{sub_start}_{sub_end}.jpg"),
                dpi = 300)


def plot_timeseries_suews_fluxobs(
    var_to_plot, up_flux_file, sub_start, sub_end,
    f_dir, df_output):
    
    ''' Plots timeseries of a flux of choice for SUEWS and Obs.'''

    plt.rcParams.update({'font.size': 14})

    # Center grid cell is always 85 in case of 13x13 grid cell
    grid_id_sel = 85

    # Read flux tower data
    df_flux = pd.read_csv(up_flux_file, index_col=0, parse_dates=True)

    fig, axes = plt.subplots(1, 1, figsize=(15,7))

    # Select required obs
    obs_sel = df_flux.loc[sub_start:sub_end, var_to_plot]

    # Plot observed fluxes.
    axes.plot(obs_sel, color = '0.2', label='Obs', lw=3)


    # Add the modelled fluxes
    list_grid = pd.to_numeric(df_output.index.levels[0], downcast="integer")
    df_output.index = df_output.index.set_levels(list_grid, level=0)
    df_output = df_output.sort_index()

    suews_sel = df_output.loc[grid_id_sel, [var_to_plot]]\
        .loc[sub_start:sub_end]

    axes.plot(suews_sel, color='red',lw=2, label='SUEWS', ls='-.')

    # Add title
    axes.set_title(var_to_plot)

    # Also add some statistics
    tmp = pd.merge(suews_sel,pd.DataFrame(obs_sel), how='inner', left_index=True, right_index=True)
    corr = np.round(tmp[var_to_plot+'_x'].corr(tmp[var_to_plot+'_y']),2)
    bias = np.round((tmp[var_to_plot+'_x']-tmp[var_to_plot+'_y']).mean(),2)
    print(corr, bias)

    axes.set_title(f'Correlation: {corr} | Bias: {bias} ',loc='right')

    axes.set_ylabel('Flux [W/m2]')

    axes.legend()

    plt.tight_layout()

    fig.savefig(os.path.join(
        f_dir,
        f"plot_timeseries_suews_fluxobs_{sub_start}_{sub_end}.jpg"),
                dpi = 300)


def plot_diurnal_cycle_flux_suews_fluxobs(
    up_flux_file, vars_to_plot, sub_start, sub_end, f_dir, df_output
    ):
    
    ''' Plots diurnal cycle of obs and suews fluxes, for grid cell
        corresponding to the flux tower location.'''
    
    plt.rcParams.update({'font.size': 14})
    

    # Center grid cell is always 85 in case of 13x13 grid cell
    grid_id_sel = 85

    # Read flux tower data
    # When final, remove synthetic series created below
    df_flux = pd.read_csv(up_flux_file, index_col=0, parse_dates=True)

    fig, axes = plt.subplots(
        1, 
        (len(vars_to_plot)), 
        figsize=((len(vars_to_plot))*5,5)
        )
    for v_i, v in enumerate(vars_to_plot):

        # Select required obs
        obs_sel = df_flux.loc[sub_start:sub_end, v]

        # Plot observed fluxes.
        obs_mean = pd.DataFrame(obs_sel.groupby(obs_sel.index.hour).mean())
        obs_std = pd.DataFrame(obs_sel.groupby(obs_sel.index.hour).std())

        axes[v_i].plot(obs_mean.index,obs_mean[v], color = '0.2', label='Obs')
        axes[v_i].fill_between(obs_mean.index,
                            obs_mean[v]-obs_std[v],
                            obs_mean[v]+obs_std[v],
                            color='0.2',
                            alpha=0.1)

        # Add the modelled fluxes as black dots / bars
        list_grid = pd.to_numeric(df_output.index.levels[0], downcast="integer")
        df_output.index = df_output.index.set_levels(list_grid, level=0)
        df_output = df_output.sort_index()

        suews_sel = df_output.loc[grid_id_sel, [v]]\
            .loc[sub_start:sub_end]
        suews_mean = suews_sel.groupby(suews_sel.index.hour).mean()
        suews_std = suews_sel.groupby(suews_sel.index.hour).std()

        axes[v_i].errorbar(suews_mean.index,suews_mean[v], suews_std[v], 
                           linestyle='None', marker='^', color='red',lw=2, label='SUEWS')

        axes[v_i].set_title(v)
    
    for ax_i in axes:
        ax_i.set_xlabel('Hour of the day (UTC)')
    axes[0].set_ylabel('Flux [W/m²]')

    axes[0].legend(loc='upper left')

    plt.tight_layout()
    
    fig.savefig(os.path.join(
        f_dir,
        f"plot_diurnal_cycle_flux_suews_fluxobs_{sub_start}_{sub_end}.jpg"),
                dpi = 300)


def plot_timeseries_mutliple_suews_vars_grid_cell(
    meteo_type_1, 
    meteo_type_2, 
    grid_id_sel, 
    sub_start, 
    sub_end,
    vars_to_plot, 
    f_dir,
    o_dir,
    start_date,
    end_date,
    ):
    
    ''' Plot selected output variables as timeseries for two supy simulations'''
        
    plt.rcParams.update({'font.size': 14})
    fig, axes = plt.subplots(len(vars_to_plot), 1, figsize=(15,3*len(vars_to_plot)))
    
    # Define the output string
    df_output_str_1  = f"{o_dir}/df_output_suews_{start_date}_{end_date}_{meteo_type_1}_1h.h5"
    df_output_str_2  = f"{o_dir}/df_output_suews_{start_date}_{end_date}_{meteo_type_2}_1h.h5"

    # Read the SUEWS output
    df_output_1     = pd.read_hdf(df_output_str_1,key="df_output_suews_1h")
    df_output_2     = pd.read_hdf(df_output_str_2,key="df_output_suews_1h")

    list_grid = pd.to_numeric(df_output_1.index.levels[0], downcast="integer")
    
    df_output_1.index = df_output_1.index.set_levels(list_grid, level=0)
    df_output_1 = df_output_1.sort_index()

    df_output_2.index = df_output_2.index.set_levels(list_grid, level=0)
    df_output_2 = df_output_2.sort_index()

    for v_i, v in enumerate(vars_to_plot):

        # Plot first simulation
        suews_1_sel = df_output_1.loc[grid_id_sel, [v]].loc[sub_start:sub_end]
        suews_1_sel.plot(ax=axes[v_i], color='#d8b365', legend=False,lw=2, label=meteo_type_1)

        # Plot second simulation
        suews_2_sel = df_output_2.loc[grid_id_sel, [v]].loc[sub_start:sub_end]
        suews_2_sel.plot(ax=axes[v_i], color='#5ab4ac', legend=False,lw=2, label=meteo_type_2)

        axes[v_i].set_ylabel(v)
    
    axes[0].legend([meteo_type_1,meteo_type_2])
    axes[0].set_title(f'Grid ID: {grid_id_sel}',loc='left')
    
    plt.tight_layout()
    
    fig.savefig(os.path.join(
        f_dir,
        f"plot_timeseries_mutliple_suews_vars_grid_cell_{grid_id_sel}_{sub_start}_{sub_end}.jpg"),
                dpi = 300)

