import geopandas as gpd
import georasters as gr
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import xarray as xr
import os, sys
import argparse
from mpl_toolkits.axes_grid1 import make_axes_locatable

script_dir = "/home/demuzmp4/Nextcloud/scripts/supy-lcz-global/visualize"
sys.path.append(script_dir)
import course_functions as cf


def get_city_from_site_list(args: argparse.Namespace) -> pd.Series:
    # check if a custom sitelist was set and read it
    if args.sitelist is not None:
        fn_sitelist = args.sitelist
    else:
        fn_sitelist = 'sitelist_urbanplumber'

    site_list = pd.read_csv(f'resources/{fn_sitelist}.csv')
    # this should always only be a one row df!
    return site_list[site_list['sitename'] == args.city].iloc[0]


class args:
    city = 'NL-Amsterdam'
    sitelist = 'sitelist_grid'
    run_type = 'grid'
    grid_boxes = 13
    grid_size = 1000


site_info = get_city_from_site_list(args)

# -------------------------------------------------
# ******    ADJUST ARGUMENTS FOR YOUR CITY    *****
# -------------------------------------------------

# set your city name and center latitude and longitude (as in the table)
city = site_info.sitename
c_lat = site_info.latitude
c_lon = site_info.longitude

# Set starting and end date (as in the table)
start_date = site_info.time_analysis_start
end_date = site_info.time_coverage_end

# -------------------------------------------------
# ******    FIXED ARGUMENTS: do NOT adjust    *****
# -------------------------------------------------
base_dir = "/home/demuzmp4/Nextcloud/scripts/supy-lcz-global/data"

i_dir = os.path.join(base_dir, city, 'input')
o_dir = os.path.join(base_dir, city, 'output', 'grid')
f_dir = '/home/demuzmp4/GoogleDrive/work-official/conferences/EGU2023/presentation'

lcz_file = os.path.join(i_dir, 'grid', "download.LCZ_Filter.tif")
grid_file = os.path.join(i_dir, 'grid', "roi_grid.shp")

suews_output = os.path.join(o_dir, "df_output_3_2b.h5")
suews_state = os.path.join(o_dir, "df_state_final_3_2b.pkl")
# suews_state  = os.path.join(o_dir, "df_state_3_2b.pkl")
grid_suews = os.path.join(o_dir, "df_roi_suews.csv")
grid_lcz = os.path.join(o_dir, "df_roi_lcz.csv")

net_file = f"{i_dir}/netatmo_amsterdam_2019_QC.csv"

"""# Read and pre-process available data"""

# Re-structure quality-controlled netatmo data
cf.restructure_netatmo(net_file, grid_file, lcz_file, start_date, end_date, qc_level='o1')

# Read the netatmo observations
net_stn_file = net_file.replace('netatmo_amsterdam_2019_QC', f'netatmo_qc_stn_{start_date}_{end_date}')
net_stn = pd.read_csv(net_stn_file, index_col=0)
print(net_stn.head())

net_obs_file = net_file.replace('netatmo_amsterdam_2019_QC', f'netatmo_qc_obs_{start_date}_{end_date}')
net_obs = pd.read_csv(net_obs_file, parse_dates=['date'], index_col=None)
net_obs.set_index('date', inplace=True)
print(net_obs.head())

# Read data generated by SUEWS simulation.
df_grid_suews = pd.read_csv(grid_suews, index_col=0)
df_grid_lcz = pd.read_csv(grid_lcz, index_col=0)
df_output = pd.read_hdf(suews_output, key="df_output")
df_state = pd.read_pickle(suews_state)

"""# A. Map grid information

## A.1. Map the grid, and netamto locations on top of the lcz map.
"""
# cf.map_lcz_grid(grid_file, lcz_file, f_dir,net_stn_file)

"""## A.2. Plot LCZ and SUEWS land cover fractions per grid cell"""
# cf.plot_gridcell_fractions(df_grid_suews, df_grid_lcz, f_dir)


"""# B. Plot SUEWS output"""

"""## B.2. Time series: two grid cells, multiple variables

For:
 - variables of choice 
 - **two** grid cells of choice,
 - sub-period of choice. If one wants the full period, then sub_start = start_date and sub_end = end_date

Each requested variable will be shown in a subplot.
"""
plt.rcParams['font.size'] = 11

gridID_1 = 84
gridID_2 = 128

var_list = ['QN', 'QS', 'QF', 'QH', 'QE']

fig, ax = plt.subplots(len(var_list), 1, figsize=(16,9), sharex=True)

for vx, v in enumerate(var_list):
    df_output.loc[gridID_1, v].plot(label=gridID_1, ax=ax[vx], color='0.2', lw=2)
    df_output.loc[gridID_2, v].plot(label=gridID_2, ax=ax[vx], color='#8dae25', lw=2)
    ax[vx].set_ylabel(v)

#ax[-1].legend(loc='upper left')
plt.tight_layout()
fig_file = f'{f_dir}/Timeseries_vars_{gridID_1}_{gridID_2}.png'
plt.savefig(fig_file, dpi=300)


"""## B.3. Spatial map: one timestamp, all grid cells, one variables

- Select one timestamp
- Provide a list of variables (1 up to 4 variables)

Intepret the spatial patterns of these variables for this timestamp. Play around a bit with different output variables (full list available [here](https://supy.readthedocs.io/en/latest/data-structure/df_output.html#df-output-variables)).
"""

# choose one time slice
time_slice = "2019-07-27 0400" # Time in UTC!
#time_slice = "2019-07-27 1300" # Time in UTC!

var_list = ['T2']
var_list = ['QF', 'QS','QH','QE']

df_res_plot = (
    df_output.swaplevel(axis=0)
    .sort_index()
    .loc[time_slice]
)

# merge supy results into geopandas dataframe for geoplotting
gdf_grid = gpd.read_file(grid_file)
gdf_grid.index = gdf_grid.id.astype(int)
df_res_plot.index = df_res_plot.index.astype(float).astype(int)
gdf_grid_plot = gdf_grid.merge(df_res_plot, left_index=True, right_index=True)

if len(var_list) == 1:
    fig, ax = plt.subplots(1, 1, figsize=(5, 5))

    divider = make_axes_locatable(ax)
    cax = divider.append_axes("right", size="5%", pad=-0.5)

    gdf_grid_plot.plot(column=var_list[0], ax=ax, legend=True, cax=cax,vmin=26, vmax=30)
    ax.set_title(var_list[0])

else:
    fig, axs = plt.subplots(1, len(var_list), figsize=(5 * len(var_list), 5),
                            sharex=True, sharey=True)
    axes = axs.ravel()
    plt.subplots_adjust(wspace=0.0002, hspace=-0.05)

    for v_i, v in enumerate(var_list):
        divider = make_axes_locatable(axes[v_i])
        cax = divider.append_axes("right", size="5%", pad=-0.5)

        gdf_grid_plot.plot(column=v, ax=axes[v_i], legend=True, cax=cax)
        axes[v_i].set_title(v)

plt.tight_layout()

fig.savefig(os.path.join(
    f_dir,
    f"map_{time_slice.replace(' ', '')}_suews_{'_'.join(var_list)}.jpg"),
    dpi=300)


"""# E. Plot SUEWS & NETATMO combined

## E.1. T2 timeseries for one SUEWS grid cell

How the function works:
1. first provide a grid cell ID of choice
2. Also select a sub-period of choice. If one wants the full period, then sub_start = start_date and sub_end = end_date

In case netatmo observations are available from that grid cell, they are added. If more # netatmo stations > 1, also the average of the netatmo stations is added (dashed purple line)

Results show:
- SUEWS output in a black line
- netatmo timeseries with a color corresponding to their LCZ-class
- Correlation and bias between SUEWS and Netatmo (avg) are provided, if netatmo stations are available.
"""

grid_id_sels = [84, 128]
#grid_id_sel = 128

sub_start = '2019-07-15 00:00:00'
sub_end = end_date

for grid_id_sel in grid_id_sels:
    cf.plot_timeseries_grid_cell(grid_id_sel, sub_start, sub_end,f_dir, net_stn, net_obs, df_output)

plt.close('all')