import geopandas as gpd
import georasters as gr
import pandas as pd
import numpy as np
import xarray as xr
import os, sys
import argparse

script_dir = "/home/demuzmp4/Nextcloud/scripts/supy-lcz-global/visualize"
sys.path.append(script_dir)
import course_functions as cf

def get_city_from_site_list(args: argparse.Namespace) -> pd.Series:

    # check if a custom sitelist was set and read it
    if args.sitelist is not None:
        fn_sitelist = args.sitelist
    else:
        fn_sitelist = 'sitelist_urbanplumber'

    site_list = pd.read_csv(f'resources/{fn_sitelist}.csv')
    # this should always only be a one row df!
    return site_list[site_list['sitename'] == args.city].iloc[0]

class args:
    city = 'NL-Amsterdam'
    sitelist = 'sitelist_grid'
    run_type = 'grid'
    grid_boxes = 13
    grid_size = 1000

site_info = get_city_from_site_list(args)

# -------------------------------------------------
# ******    ADJUST ARGUMENTS FOR YOUR CITY    *****
# -------------------------------------------------

# set your city name and center latitude and longitude (as in the table)
city       = site_info.sitename
c_lat      = site_info.latitude
c_lon      = site_info.longitude

# Set starting and end date (as in the table)
start_date = site_info.time_analysis_start
end_date   = site_info.time_coverage_end

# -------------------------------------------------
# ******    FIXED ARGUMENTS: do NOT adjust    *****
# -------------------------------------------------
base_dir = "/home/demuzmp4/Nextcloud/scripts/supy-lcz-global/data"

i_dir         = os.path.join(base_dir, city, 'input')
o_dir         = os.path.join(base_dir, city, 'output', 'grid')
f_dir         = os.path.join(base_dir, 'figs')


lcz_file      = os.path.join(i_dir, 'grid', "download.LCZ_Filter.tif")
grid_file     = os.path.join(i_dir, 'grid', "roi_grid.shp")

suews_output  = os.path.join(o_dir, "df_output_3_2b.h5")
suews_state  = os.path.join(o_dir, "df_state_final_3_2b.pkl")
#suews_state  = os.path.join(o_dir, "df_state_3_2b.pkl")
grid_suews    = os.path.join(o_dir, "df_roi_suews.csv")
grid_lcz      = os.path.join(o_dir, "df_roi_lcz.csv")

net_file      = f"{i_dir}/netatmo_amsterdam_2019_QC.csv"


"""# Read and pre-process available data"""

# Re-structure quality-controlled netatmo data
cf.restructure_netatmo(net_file, grid_file, lcz_file, start_date, end_date, qc_level = 'o1')

# Read the netatmo observations
net_stn_file = net_file.replace('netatmo_amsterdam_2019_QC', f'netatmo_qc_stn_{start_date}_{end_date}')
net_stn = pd.read_csv(net_stn_file, index_col=0)
print(net_stn.head())

net_obs_file = net_file.replace('netatmo_amsterdam_2019_QC', f'netatmo_qc_obs_{start_date}_{end_date}')
net_obs = pd.read_csv(net_obs_file, parse_dates=['date'], index_col=None)
net_obs.set_index('date', inplace=True)
print(net_obs.head())

# Read data generated by SUEWS simulation.
df_grid_suews = pd.read_csv(grid_suews, index_col=0)
df_grid_lcz   = pd.read_csv(grid_lcz, index_col=0)
df_output     = pd.read_hdf(suews_output,key="df_output")
df_state      = pd.read_pickle(suews_state)

"""# A. Map grid information

## A.1. Map the grid, and netamto locations on top of the lcz map.
"""
cf.map_lcz_grid(grid_file, lcz_file, f_dir,net_stn_file)

"""## A.2. Plot LCZ and SUEWS land cover fractions per grid cell"""
cf.plot_gridcell_fractions(df_grid_suews, df_grid_lcz, f_dir)

"""## A.3. Print urban land cover characteristics for flux tower grid cell

Do these correspond to the site characteristics provided by Urban Plumber?
Find your site and properties [here](https://urban-plumber.github.io/sites). Use this information to interpret your model results (compared to obs)
"""

# Flux site grid cell is the one in the center of the domain (id = 85)
grid_id = 84

# Get properties that are relevant.
site_land_cover = df_grid_suews.loc[
    grid_id,
    ['Paved (-)', 'Buildings (-)', 'Grass (-)', 'Deciduous trees (-)', 'Evergreen trees (-)', 'Bare soil (-)', 'Water (-)']
]
print(site_land_cover)

"""## A.4. Check df_state, for emissionMethod and popdensity"""
df_state = pd.read_pickle(suews_state)

grid_ids = [84, 128]
state_vars = ["emissionsmethod", 'popdensdaytime', 'popdensnighttime']
#state_var = 'popdensdaytime'

idx = pd.IndexSlice

for gi in grid_ids:
    for sv in state_vars:
        print(f"**** {gi}: {sv}")
        print(df_state.loc[idx[:,gi], sv])



"""# B. Plot SUEWS output

## B.1. Time series: one grid cell, multiple variables

For:
 - variables of choice 
 - one grid cell of choice,
 - sub-period of choice. If one wants the full period, then sub_start = start_date and sub_end = end_date

All variables are shown in one plot.

Available variables - obtained via *print(df_output.columns)* - are: 

['Kdown', 'Kup', 'Ldown', 'Lup', 'Tsurf', 'QN', 'QF', 'QS', 'QH', 'QE',
       'QHlumps', 'QElumps', 'QHresis', 'Rain', 'Irr', 'Evap', 'RO', 'TotCh',
       'SurfCh', 'State', 'NWtrState', 'Drainage', 'SMD', 'FlowCh', 'AddWater',
       'ROSoil', 'ROPipe', 'ROImp', 'ROVeg', 'ROWater', 'WUInt', 'WUEveTr',
       'WUDecTr', 'WUGrass', 'SMDPaved', 'SMDBldgs', 'SMDEveTr', 'SMDDecTr',
       'SMDGrass', 'SMDBSoil', 'StPaved', 'StBldgs', 'StEveTr', 'StDecTr',
       'StGrass', 'StBSoil', 'StWater', 'Zenith', 'Azimuth', 'AlbBulk', 'Fcld',
       'LAI', 'z0m', 'zdm', 'UStar', 'Lob', 'RA', 'RS', 'Fc', 'FcPhoto',
       'FcRespi', 'FcMetab', 'FcTraff', 'FcBuild', 'FcPoint', 'QNSnowFr',
       'QNSnow', 'AlbSnow', 'QM', 'QMFreeze', 'QMRain', 'SWE', 'MeltWater',
       'MeltWStore', 'SnowCh', 'SnowRPaved', 'SnowRBldgs', 'Ts', 'T2', 'Q2',
       'U10', 'RH2']
       
More information on the meaning of these output variables [here](https://supy.readthedocs.io/en/latest/data-structure/df_output.html#df-output-variables).
"""

grid_id_sel = 84
grid_id_sel = 153

df_output.loc[grid_id_sel]['QF'].plot()
df_output.loc[153]['QF'].plot()

# Show available SUEWS variables:
#print(df_output.columns)


sub_start = start_date
sub_end = end_date
var_list = ['QN','QF', 'QS', 'QH', 'QE']
#var_list = ['QF']

cf.plot_timeseries_suews_vars_grid_cell(grid_id_sel, sub_start, sub_end,
                                        var_list, df_output, f_dir)

"""## B.2. Time series: two grid cells, multiple variables

For:
 - variables of choice 
 - **two** grid cells of choice,
 - sub-period of choice. If one wants the full period, then sub_start = start_date and sub_end = end_date
 
Each requested variable will be shown in a subplot.
"""

var_list = ['QN', 'QS', 'QF', 'QE','QH','Ts', 'T2']
gridID_1 = 153
gridID_2 = 85

fig, axes = plt.subplots(len(var_list),1,figsize=[12, 4*len(var_list)],
                            sharex=True)

    for v_i, v in enumerate(var_list):

        if len(var_list) == 1:
            ax_target = axes
        else:
            ax_target = axes[v_i]

        df_output.loc[gridID_1, v]\
            .plot(ax=ax_target, label=gridID_1)\
            .legend(loc='upper left')

        df_output.loc[gridID_2, v]\
            .plot(ax=ax_target, label=gridID_2)\
            .legend(loc='upper left')
        ax_target.set_ylabel(v)

plt.tight_layout()

sub_start = start_date
sub_end = end_date

cf.plot_timeseries_suews_vars_two_cells(gridID_1, gridID_2, sub_start, sub_end, 
                                        var_list, df_output, f_dir)

"""## B.3. Spatial map: one timestamp, all grid cells, up to 4 variables

- Select one timestamp
- Provide a list of variables (1 up to 4 variables)

Intepret the spatial patterns of these variables for this timestamp. Play around a bit with different output variables (full list available [here](https://supy.readthedocs.io/en/latest/data-structure/df_output.html#df-output-variables)).
"""

# choose one time slice
time_slice = "2019-07-27 0400" # Time in UTC!
var_list = ['Ts','QH','SMD','QE']
#var_list = ['QH']

cf.map_time_slice_suews(time_slice, var_list, 
                        df_output, grid_file, f_dir)

"""## B.4. Intra-SUEWS-grid variability, for variable of choice

As seen above, SUEWS grid cells typically consist out of different LCZ classes, which are converted to urban canopy parameters (e.g. fractions of pavement, building, grass, trees, and other properties).

As such, it is not possible to plot the intra-LCZ variability for the SUEWS output.

The alternative is to plot the intra-grid cell variability, binned according to the total imperviousness of a grid cell (= sum of paved + building fraction). 

This is done below, for the daily mean (all time steps), day-time (incoming shortwave radiation Kdown > 0) and (c) night-time (Kdown = 0).

Any (sub-)period can be selected. If one wants the full period, then sub_start = start_date and sub_end = end_date

The result provides:
- three panels, for daily mean, day-time and night-time.
- the filled circles refer to the mean
- the bars are +/- one standard deviation
- the purple numbers in the first panel refer to the number of grid cells per imperviousness class

*Note:* the x-axis refers to the impervious bin. Bin 0.05 refers to an imperviousness of [0,0.1], 0.15 to [0.1,0.2] and so on ...
"""

sub_start = start_date
sub_end = end_date
#var = 'T2'; vmin=0; vmax=50
var = 'QH'; vmin=0; vmax=400
#var = 'QF'; vmin=0; vmax=100

cf.plot_intra_suews_grid_variability(var, sub_start, sub_end,
                                  df_grid_suews, df_output, f_dir,
                                  vmin, vmax)

"""# C. Plot NETATMO observations

## C.1. Intra-LCZ T2 variability

Explore the T2 distribution for (a) daily mean values, (b) daytime (incoming shortwave radiation Kdown > 0) and (c) night-time (Kdown = 0) per local climate zone (LCZ) for Netatmo citizen weather stations. This is similar to Fig. 5 in [Fenner et al. (2017)](http://www.schweizerbart.de/papers/metz/detail/prepub/88058/Intra_and_inter_local_climate_zone_variability_of_?af=crossref), although day/night-time definitions are different, and we only present +/- one standard deviation, in contrast to the full distribution (box plot) in the paper.

Any (sub-)period can be selected. If one wants the full period, then sub_start = start_date and sub_end = end_date

The result provides:
- three panels, for daily mean, day-time and night-time.
- the filled circles refer to the mean
- the bars are +/- one standard deviation
- the purple numbers in the first panel refer to the number of netatmo station per LCZ class
"""

sub_start = start_date
sub_end = end_date
var = 'T2'

cf.plot_intra_lcz_variability(var, sub_start, sub_end,
                              net_obs, net_stn, df_output, f_dir)

"""# D. Plot URBAN PLUMBER flux observations

## D.1. Timeseries

Plot the timeseries of variables of choice, as observed by the flux tower. Quite a number of variables are available, yet for this course we will focus on the radiation and energy balance components only (which are given the same variable names as they are produced by SUEWS):


* Kdown [W/m2]: downward short-wave radiation
* LWdown [W/m2]: downward long-wave radiation
* SWup [W/m2]: downward short-wave radiation 
* LWup [W/m2]: upward long-wave radiation
* Qn [W/m2]: Net radiation 
* QE [W/m2]: Latent heat flux 
* QH [W/m2]: Sensible heat flux
* QS [W/m2]: Storage heat flux (not measured, residual from QN - QH - QLE)


Any (sub-)period can be selected. If one wants the full period, then sub_start = start_date and sub_end = end_date

The result provides:

- One panel, timeseries of X variables
"""

# Select period of interest
sub_start = start_date
sub_end = end_date

# Variables to plot
var_list = ['QN', 'QH', 'QE', 'QS']

cf.plot_timeseries_flux_obs(up_flux_file, sub_start, sub_end, 
                                         var_list, df_output, f_dir)

"""## D.2. Diurnal average plots

Plot the average diurnal cycle for QN (net incoming radiation), QH (sensible heat flux), QE (latent heat flux) and QS (storage heat flux), as observed by the flux tower.

Any (sub-)period can be selected. If one wants the full period, then sub_start = start_date and sub_end = end_date

The result provides:

- four panels, one per flux component
- the full line refers to the hourly mean
- the shaded areas are +/- one standard deviation around the mean
"""

# Select period of interest
sub_start = start_date
sub_end = end_date


cf.plot_diurnal_cycle_flux_obs(up_flux_file, sub_start, sub_end, f_dir)

"""# E. Plot SUEWS & NETATMO combined

## E.1. T2 timeseries for one SUEWS grid cell

How the function works:
1. first provide a grid cell ID of choice
2. Also select a sub-period of choice. If one wants the full period, then sub_start = start_date and sub_end = end_date

In case netatmo observations are available from that grid cell, they are added. If more # netatmo stations > 1, also the average of the netatmo stations is added (dashed purple line)

Results show:
- SUEWS output in a black line
- netatmo timeseries with a color corresponding to their LCZ-class
- Correlation and bias between SUEWS and Netatmo (avg) are provided, if netatmo stations are available.
"""

grid_id_sel = 51
sub_start = start_date
sub_end = end_date

cf.plot_timeseries_grid_cell(grid_id_sel, sub_start, sub_end,f_dir, net_stn, net_obs, df_output)

"""## E.2. Average diurnal cycles for T2, for one SUEWS grid cell

How the function works:
1. first provide a grid cell ID of choice
2. Also select a sub-period of choice. If one wants the full period, then sub_start = start_date and sub_end = end_date

In case netatmo observations are available from that grid cell, they are automatically added. If more # netatmo stations > 1, also the average of the netatmo stations is added (dashed purple line).

Results depict the following (over the sub-period of interest):
- the black triangles are the hourly average, for the SUEWS grid cell
- the black bars represent the average hourly +/- one standard deviation around the mean, for the SUEWS grid cell
- the LCZ-colored tick lines present the hourly average for each available netatmo station in the grid cell
- the LCZ-colored shaded areas represent the average hourly +/- one standard deviation around the mean, for each available netatmo station in the grid cell
"""

grid_id_sel = 83
sub_start = start_date
sub_end = end_date

cf.plot_diurnal_cycle_grid_cell(grid_id_sel, sub_start, sub_end, f_dir, net_stn, net_obs, df_output)

"""## E.3. Intra-grid variability for SUEWS and NETATMO for T2.

As in Section A.5 above, but now also including the Netatmo stations.

For SUEWS, a grid cell is binned according to its degree of imperviousness.
To include Netatmo data, all netatmo stations that fall within a SUEWS grid cell, and thus imperviousness bin, are added.

This is again done for the daily mean (all time steps), day-time (incoming shortwave radiation Kdown > 0) and (c) night-time (Kdown = 0).

Any (sub-)period can be selected. If one wants the full period, then sub_start = start_date and sub_end = end_date

The result provides:
- three panels, for daily mean, day-time and night-time.
- SUEWS is output in black, Netatmo in grey
- the filled circles refer to the mean
- the bars are +/- one standard deviation
- purple numbers: number of SUEWS grid cells per imperviousness bin
- pink numbers:  number of netatmo station per imperviousness bin

*Note:* the x-axis refers to the impervious bin. Bin 0.05 refers to an imperviousness of [0,0.1], 0.15 to [0.1,0.2] and so on ...
"""

sub_start = start_date
sub_end = end_date
var = 'T2'; vmin=0; vmax=50

cf.plot_intra_suews_netatmo_variability(var, sub_start, sub_end,
                                        net_stn, net_obs, df_grid_suews, df_output, f_dir,
                                        vmin, vmax)

"""# F. Plot SUEWS & FLUXES combined

## F.1. Time series per flux

As in D.1., but:
- only for one flux of choice (QN, QH, QE or QS)
- adding the modelled suews fluxes
- and adding some basic statistics (correlation and bias)

Any (sub-)period can be selected. If one wants the full period, then sub_start = start_date and sub_end = end_date
"""

sub_start = start_date
sub_end = end_date

var_to_plot = 'QE'

cf.plot_timeseries_suews_fluxobs(var_to_plot, up_flux_file, sub_start, sub_end, 
                              f_dir, df_output)

"""## F.2. Average diurnal cycles

As in D.2., but this time also adding the modelled fluxes for the grid cell corresponding to the location of the flux tower.
"""

sub_start = start_date
sub_end = end_date

#vars_to_plot = ['QN', 'QH', 'QE', 'QS']
vars_to_plot = ['Kdown', 'Kup', 'Ldown', 'Lup']

cf.plot_diurnal_cycle_flux_suews_fluxobs(
    up_flux_file, vars_to_plot, sub_start, sub_end, f_dir, df_output)

"""# G. Compare two SUPY simulations

## G.1. Timeseries for two SUPY simulations

Plot selected output variables as timeseries for two supy simulations
"""

# Set the meteoforcing outputs you'd like to compare
meteo_type_1 = "metforcing"
meteo_type_2 = "era5_raw"

# Set the variables you are interested in
vars_to_plot = ['Kup', 'Lup', 'QH','QE']

# Set the grid cell of interest
grid_id_sel = 153

# Set subperiod of interest
sub_start = start_date
sub_end = end_date

cf.plot_timeseries_mutliple_suews_vars_grid_cell(
    meteo_type_1, meteo_type_2, grid_id_sel, 
    sub_start, sub_end, var_list, 
    f_dir, o_dir, start_date, end_date,
    )